import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e0e3e7",
        "on-tertiary-fixed": "#2f1500",
        "on-secondary-container": "#5b4400",
        "surface-container-low": "#181c1f",
        "surface-tint": "#ffb95f",
        "on-tertiary-fixed-variant": "#6e3900",
        "surface-bright": "#363a3d",
        "on-secondary-fixed-variant": "#5a4300",
        "tertiary-container": "#ff9837",
        "on-surface": "#e0e3e7",
        "tertiary-fixed": "#ffdcc3",
        "on-primary-container": "#613b00",
        "error": "#ffb4ab",
        "primary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb77d",
        "primary-container": "#f59e0b",
        "background": "#101417",
        "surface-container-high": "#262a2e",
        "on-secondary": "#3f2e00",
        "on-tertiary-container": "#6a3700",
        "error-container": "#93000a",
        "outline": "#a08e7a",
        "inverse-on-surface": "#2d3134",
        "on-tertiary": "#4d2600",
        "secondary-container": "#e4ae00",
        "tertiary": "#ffc08e",
        "secondary": "#ffca45",
        "on-secondary-fixed": "#251a00",
        "outline-variant": "#534434",
        "on-error-container": "#ffdad6",
        "on-primary": "#472a00",
        "surface-dim": "#101417",
        "on-primary-fixed-variant": "#653e00",
        "on-surface-variant": "#d8c3ad",
        "on-error": "#690005",
        "surface": "#101417",
        "on-background": "#e0e3e7",
        "primary-fixed-dim": "#ffb95f",
        "primary": "#ffc174",
        "surface-container": "#1c2023",
        "on-primary-fixed": "#2a1700",
        "secondary-fixed": "#ffdf9a",
        "surface-variant": "#313539",
        "secondary-fixed-dim": "#f7be1d",
        "surface-container-highest": "#313539",
        "surface-container-lowest": "#0b0f12",
        "inverse-primary": "#855300"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-tablet": "2rem",
        "margin-desktop": "3.5rem",
        "gutter-desktop": "2rem",
        "gutter": "1.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin": "1rem"
      },
      fontFamily: {
        "sans": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline": ["var(--font-syne)", "Syne", "sans-serif"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Syne"],
        "display-hero-mobile": ["Syne"],
        "headline-md": ["Syne"],
        "label-xs": ["Inter"],
        "title-sm": ["Inter"],
        "label-lg": ["Inter"],
        "headline-lg": ["Syne"],
        "title-md": ["Inter"],
        "headline-sm": ["Syne"],
        "display-hero": ["Syne"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "0.01em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "title-sm": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
