import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "surface-variant": "#333539",
        "surface-tint": "#e9c349",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#d0c5af",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        outline: "#99907c",
        "outline-variant": "#4d4635",
        primary: "#f2ca50",
        "on-primary": "#3c2f00",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "inverse-primary": "#735c00",
        secondary: "#fabc4d",
        "on-secondary": "#432c00",
        "secondary-container": "#bd8718",
        "on-secondary-container": "#3a2600",
        tertiary: "#ffc37b",
        "on-tertiary": "#472a00",
        "tertiary-container": "#f7a00f",
        "on-tertiary-container": "#633d00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "secondary-fixed": "#ffdead",
        "secondary-fixed-dim": "#fabc4d",
        "on-secondary-fixed": "#281900",
        "on-secondary-fixed-variant": "#604100",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        background: "#111317",
        "on-background": "#e2e2e8",
        // Verdes usados puntualmente para indicadores "en vivo" / sincronizado.
        success: "#10b981",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        margin: "1.5rem",
        "margin-tablet": "2rem",
        "margin-desktop": "2.5rem",
        "margin-compact": "1.5rem",
        gutter: "1.5rem",
        "gutter-dense": "1rem",
        "gutter-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        headline: ["var(--font-outfit)", "Outfit", "sans-serif"],
        mono: ["var(--font-jbmono)", "JetBrains Mono", "monospace"],
        "display-hero": ["Outfit"],
        "display-hero-mobile": ["Outfit"],
        "headline-xl": ["Outfit"],
        "headline-lg": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "headline-md": ["Outfit"],
        "headline-sm": ["Outfit"],
        "title-md": ["Hanken Grotesk"],
        "title-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "label-lg": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "label-xs": ["Hanken Grotesk"],
        "label-caps": ["Outfit"],
        "data-mono": ["JetBrains Mono"],
        "data-mono-sm": ["JetBrains Mono"],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "22px", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-xs": ["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "18px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "data-mono-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
